const EVENTS = {
  connection: "connection",
  CLIENT: {
    CREATE_ROOM: "CREATE_ROOM",
    SEND_ROOM_MESSAGE: "SEND_ROOM_MESSAGE",
    JOIN_ROOM: "JOIN_ROOM",
    SEND_PRIVATE_MESSAGE: "SEND_PRIVATE_MESSAGE",
    SHOW_CONNECTED_USERS: "SHOW_CONNECTED_USERS",
  },
  SERVER: {
    ROOMS: "ROOMS",
    JOINED_ROOM: "JOINED_ROOM",
    ROOM_MESSAGE: "ROOM_MESSAGE",
    PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
    CONNECTED_USERS: "CONNECTED_USERS",
  },
};

export default EVENTS;
